spring:
    application:
        name: PracticeModsenJava

    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/pizza_db
        username: postgres
        password: postgres

    liquibase:
        change-log: classpath:db/changelog/db.changelog-master.xml
