spring:
  #  application:
  #    name: PracticeModsenJava

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pizza_db
    username: postgres
    password: postgres

  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

app:
  token-access:
    key-secret: AFAKJFsdfsdAfasfksdafsasdfkhkadsAKSfsdgkljsghdsHGHSDKGHDKSHGDKSGdkshKHGksdhgkds1DSGDSGDSGasfsNFKASNfkas
    lifetime: 300
  token-refresh:
    lifetime: 86400
#  exception:
#    code:
#      throwable: 1
#      data-integrity-violation-exception: 2
#      method-argument-not-valid-exception: 3
#
#      services:
#        authentication:
#          loginUser: 41
#          signUpUser: 42
#
#
#        category:
#
#            loginUser: 41
#            signUpUser: 42
#            logoutUser: 43
#            refreshToken: 44
#
##          resource-not-found-exception:
##          resource-state-exception:
#        orderItem:
#
#
#        order:
#
#
#        product:
