spring:
    application:
        name: authentication-server

    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/authentication_server_db
        username: postgres
        password: postgres

    liquibase:
        change-log: classpath:db/changelog/db.changelog-master.xml

authentication-server:
    jwt-secret: asfasdgKHASFfnjaskdkAdsalsd
    jwtExpirationMs: 86400000
    authentication-server.pre-flight-request-max-age: 3600
